'use server'

import { revalidatePath } from 'next/cache';
import { createClient } from '@/utils/supabase/server';
import { redirect } from 'next/navigation';
import { createNotification } from '@/utils/notifications';

export async function createPurchaseOrder(prevState: any, formData: FormData) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return { error: 'Unauthorized' };

  const vendor_id = formData.get('vendor_id') as string;
  const description = formData.get('description') as string;
  const amount = formData.get('amount') as string;
  const issued_date = formData.get('issued_date') as string;
  const due_date = formData.get('due_date') as string;
  const project_id = formData.get('project_id') as string;

  if (!vendor_id || !amount || !issued_date) {
    return { error: 'Vendor, amount, and issued date are required.' };
  }

  // po_number is auto-generated by the DB trigger
  const { data: newPO, error } = await supabase.from('purchase_orders').insert({
    vendor_id,
    project_id: project_id || null,
    description,
    amount: parseFloat(amount),
    issued_date,
    due_date: due_date || null,
    status: 'draft',
    created_by: user.id
  }).select('id').single();

  if (error) {
    console.error('Error creating PO:', error);
    return { error: error.message };
  }

  // Audit log
  await supabase.from('audit_logs').insert({
    entity_type: 'purchase_order',
    entity_id: newPO.id,
    action: 'CREATE',
    changes: { after: { vendor_id, amount, status: 'draft' } },
    performed_by: user.id
  });

  await createNotification({
    type: 'po',
    title: '📋 Purchase Order Created',
    message: `A new purchase order was drafted.`,
    link: `/dashboard/purchase-orders/${newPO.id}`,
    created_by: user.id
  });

  revalidatePath('/dashboard/purchase-orders');
  redirect(`/dashboard/purchase-orders/${newPO.id}`);
}

export async function updatePOStatus(poId: string, status: string) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return { error: 'Unauthorized' };

  const { error } = await supabase
    .from('purchase_orders')
    .update({ status, updated_at: new Date().toISOString() })
    .eq('id', poId);

  if (error) return { error: error.message };

  await supabase.from('audit_logs').insert({
    entity_type: 'purchase_order',
    entity_id: poId,
    action: 'UPDATE',
    changes: { after: { status } },
    performed_by: user.id
  });

  await createNotification({
    type: 'po',
    title: `📋 PO Status Updated`,
    message: `Purchase order status changed to ${status}.`,
    link: `/dashboard/purchase-orders/${poId}`,
    created_by: user.id
  });

  revalidatePath(`/dashboard/purchase-orders/${poId}`);
  return { success: true };
}

export async function assignProjectToPO(poId: string, projectId: string | null) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return { error: 'Unauthorized' };

  const { error } = await supabase
    .from('purchase_orders')
    .update({ project_id: projectId, updated_at: new Date().toISOString() })
    .eq('id', poId);

  if (error) return { error: error.message };

  await supabase.from('audit_logs').insert({
    entity_type: 'purchase_order',
    entity_id: poId,
    action: 'UPDATE',
    changes: { after: { project_id: projectId } },
    performed_by: user.id
  });

  revalidatePath(`/dashboard/purchase-orders/${poId}`);
  return { success: true };
}
