'use server'

import { revalidatePath } from 'next/cache';
import { createClient } from '@/utils/supabase/server';
import { redirect } from 'next/navigation';
import { createNotification } from '@/utils/notifications';
import { recordAuditLog } from '@/utils/audit';

export async function createPurchaseOrder(prevState: any, formData: FormData) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return { error: 'Unauthorized' };

  const vendor_id = formData.get('vendor_id') as string;
  const description = formData.get('description') as string;
  const amount = formData.get('amount') as string;
  const issued_date = formData.get('issued_date') as string;
  const due_date = formData.get('due_date') as string;
  const project_id = formData.get('project_id') as string;

  if (!vendor_id || !amount || !issued_date) {
    return { error: 'Vendor, amount, and issued date are required.' };
  }

  // NDA Gate — vendor must have an approved Signed NDA before any PO can be created
  const { data: ndaDoc } = await supabase
    .from('vendor_documents')
    .select('status')
    .eq('vendor_id', vendor_id)
    .eq('doc_type', 'signed_nda')
    .eq('status', 'approved')
    .is('archived_at', null)
    .maybeSingle();

  if (!ndaDoc) {
    return { error: 'Cannot create PO: This vendor does not have an approved Signed NDA on file. Please submit and have the NDA approved first.' };
  }

  // Auto-assign the internal entity (subsidiary)
  const { data: entity } = await supabase
    .from('internal_entities')
    .select('id')
    .limit(1)
    .single();

  // Fetch vendor status and currency
  const { data: vendor } = await supabase
    .from('vendors')
    .select('status, currency')
    .eq('id', vendor_id)
    .single();

  if (!vendor || vendor.status !== 'active') {
    return { error: 'Cannot create PO: This vendor is not currently active. Vendors must be activated (Accredited) before purchase orders can be issued.' };
  }

  const currency = vendor.currency || 'PHP';

  // po_number is auto-generated by the DB trigger
  const { data: newPO, error } = await supabase.from('purchase_orders').insert({
    vendor_id,
    project_id: project_id || null,
    description,
    amount: parseFloat(amount),
    issued_date,
    due_date: due_date || null,
    status: 'draft',
    currency,
    internal_entity_id: entity?.id || null,
    created_by: user.id
  }).select('id').single();

  if (error) {
    console.error('Error creating PO:', error);
    return { error: error.message };
  }

  // Audit log
  await recordAuditLog({
    entity_type: 'purchase_order',
    entity_id: newPO.id,
    action: 'CREATE',
    changes: { after: { vendor_id, amount, status: 'draft', currency } },
    performed_by: user.id
  });

  await createNotification({
    type: 'po',
    title: '📋 Purchase Order Created',
    message: `A new purchase order was drafted.`,
    link: `/dashboard/purchase-orders/${newPO.id}`,
    created_by: user.id
  });

  revalidatePath('/dashboard/purchase-orders');
  redirect(`/dashboard/purchase-orders/${newPO.id}`);
}

export async function updatePOStatus(poId: string, status: string) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return { error: 'Unauthorized' };

  const { error } = await supabase
    .from('purchase_orders')
    .update({ status, updated_at: new Date().toISOString() })
    .eq('id', poId);

  if (error) return { error: error.message };

  await recordAuditLog({
    entity_type: 'purchase_order',
    entity_id: poId,
    action: 'UPDATE',
    changes: { after: { status } },
    performed_by: user.id
  });

  await createNotification({
    type: 'po',
    title: `📋 PO Status Updated`,
    message: `Purchase order status changed to ${status}.`,
    link: `/dashboard/purchase-orders/${poId}`,
    created_by: user.id
  });

  revalidatePath(`/dashboard/purchase-orders/${poId}`);
  return { success: true };
}

export async function assignProjectToPO(poId: string, projectId: string | null) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return { error: 'Unauthorized' };

  const { error } = await supabase
    .from('purchase_orders')
    .update({ project_id: projectId, updated_at: new Date().toISOString() })
    .eq('id', poId);

  if (error) return { error: error.message };

  await recordAuditLog({
    entity_type: 'purchase_order',
    entity_id: poId,
    action: 'UPDATE',
    changes: { after: { project_id: projectId } },
    performed_by: user.id
  });

  revalidatePath(`/dashboard/purchase-orders/${poId}`);
  return { success: true };
}
