import * as React from "react";
import { Link, Section, Text } from "@react-email/components";
import { EmailLayout, styles } from "./layout";

export interface PrPendingFinanceEmailProps {
  prNumber: string;
  vendorName: string;
  purpose: string;
  amountLabel?: string | null;
  downpaymentLabel?: string | null;
  downpaymentPercent?: number | null;
  reviewUrl: string;
}

/**
 * Sent to the finance pool when a PR passes the admin stage and is pending the
 * finance budget check before it can be converted to a PO. The action lives
 * in-app.
 */
export function PrPendingFinanceEmail({
  prNumber,
  vendorName,
  purpose,
  amountLabel,
  downpaymentLabel,
  downpaymentPercent,
  reviewUrl,
}: PrPendingFinanceEmailProps) {
  return (
    <EmailLayout
      preview={`PR ${prNumber} is pending the finance review`}
      footerQuestionText="This is an automated email generated by TVPH ERP. Please do not reply directly to this message."
    >
      <Text style={styles.heading}>Dear Finance,</Text>
      <Text style={styles.paragraph}>
        The Purchase Request for {vendorName} has been approved by the admin and
        now requires the finance budget check before it can proceed.
      </Text>
      <Section style={styles.panel}>
        <Text style={styles.meta}>PR Number: {prNumber}</Text>
        <Text style={styles.meta}>Vendor Name: {vendorName}</Text>
        <Text style={styles.meta}>Purpose: {purpose}</Text>
        {amountLabel ? <Text style={styles.meta}>Amount: {amountLabel}</Text> : null}
        <Text style={{ ...styles.meta, ...(downpaymentLabel ? { color: "#b45309", fontWeight: 700 } : {}) }}>
          {downpaymentLabel
            ? `Downpayment: ${downpaymentPercent ? `${downpaymentPercent}% — ` : ""}${downpaymentLabel}`
            : "Downpayment: None"}
        </Text>
      </Section>
      <Text style={styles.paragraph}>
        Kindly review the amount and approve it so the request can be converted
        into a purchase order, or reject it with a reason if any adjustments are
        required.
      </Text>
      <Section style={{ margin: "8px 0 16px" }}>
        <Link href={reviewUrl} style={styles.button}>
          Review &amp; approve
        </Link>
      </Section>
    </EmailLayout>
  );
}

export default PrPendingFinanceEmail;
